version: 2.1

orbs:
  ruby: circleci/ruby@2.0.0
  node: circleci/node@5.1.0

executors:
  rossta-ruby-node:
    working_directory: ~/rossta/rossta.github.com
    docker:
      - image: cimg/ruby:3.1.2-node
    environment:
      USER_NAME: rossta
      USER_EMAIL: ross@rossta.net

commands:
  install-node-dependencies:
    description: Install and cache npm dependencies
    steps:
      - node/install-packages:
          pkg-manager: yarn
          include-branch-in-cache-key: false
      - run:
          name: Which yarn?
          command: yarn --version
      - run:
          name: Which node?
          command: node --version
      - run:
          name: Which npm?
          command: npm --version
  install-ruby-dependencies:
    description: Install and cache Bundler dependencies
    steps:
      - ruby/install-deps
      - run:
          name: Which ruby?
          command: ruby --version
      - run:
          name: Which bundler?
          command: bundle --version

jobs:
  build:
    executor: rossta-ruby-node
    steps:
      - checkout
      - install-node-dependencies
      - install-ruby-dependencies
      - run: bin/rake build

  publish:
    executor: rossta-ruby-node
    steps:
      - checkout
      - install-node-dependencies
      - install-ruby-dependencies
      - run: git config --global -l # debug
      - run: git config --global user.email circleci@circleci
      - run: git config --global user.name CircleCI
      - run: bin/rake publish

workflows:
  version: 2
  build-site:
    jobs:
      - build:
          filters:
            branches:
              ignore: main

  publish-site:
    jobs:
      - publish:
          filters:
            branches:
              only: develop
